### ISSUE TITLE
AttributeError: 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by MuffinMedic** [anodium/discord_logger#5]
```
(discord-logger) ircbots@muffinmedic.net:~$ git clone https://github.com/anodium/discord-logger.git
Cloning into 'discord-logger'...
remote: Counting objects: 268, done.
remote: Total 268 (delta 0), reused 0 (delta 0), pack-reused 268
Receiving objects: 100% (268/268), 32.14 KiB | 0 bytes/s, done.
Resolving deltas: 100% (120/120), done.
Checking connectivity... done.
(discord-logger) ircbots@muffinmedic.net:~$ cd discord-logger/
(discord-logger) ircbots@muffinmedic.net:~/discord-logger$ ls
LICENSE  MANIFEST.in  README.md  requirements.txt  setup.py  src
(discord-logger) ircbots@muffinmedic.net:~/discord-logger$ pip --version
pip 9.0.1 from /home/ircbots/.pyenv/versions/3.6.2/envs/discord-logger/lib/python3.6/site-packages (python 3.6)
(discord-logger) ircbots@muffinmedic.net:~/discord-logger$ pip install -r requirements.txt 
Requirement already satisfied: discord.py>=0.16.0 in /home/ircbots/.pyenv/versions/3.6.2/envs/discord-logger/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: aiohttp<1.1.0,>=1.0.0 in /home/ircbots/.pyenv/versions/3.6.2/envs/discord-logger/lib/python3.6/site-packages (from discord.py>=0.16.0->-r requirements.txt (line 1))
Requirement already satisfied: websockets<4.0,>=3.1 in /home/ircbots/.pyenv/versions/3.6.2/envs/discord-logger/lib/python3.6/site-packages (from discord.py>=0.16.0->-r requirements.txt (line 1))
Requirement already satisfied: chardet in /home/ircbots/.pyenv/versions/3.6.2/envs/discord-logger/lib/python3.6/site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py>=0.16.0->-r requirements.txt (line 1))
Requirement already satisfied: multidict>=2.0 in /home/ircbots/.pyenv/versions/3.6.2/envs/discord-logger/lib/python3.6/site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py>=0.16.0->-r requirements.txt (line 1))
Requirement already satisfied: async_timeout in /home/ircbots/.pyenv/versions/3.6.2/envs/discord-logger/lib/python3.6/site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py>=0.16.0->-r requirements.txt (line 1))
(discord-logger) ircbots@muffinmedic.net:~/discord-logger$ python --version
Python 3.6.2
(discord-logger) ircbots@muffinmedic.net:~/discord-logger$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    LONG_DESCRIPTION = read('README.md').splitlines()
  File "setup.py", line 10, in read
    return open(os.path.join(os.path.dirname(__file__), fname)).read()
  File "/home/ircbots/.pyenv/versions/3.6.2/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 38: ordinal not in range(128)
(discord-logger) ircbots@muffinmedic.net:~/discord-logger$ pico README.md ### REMOVED álá
(discord-logger) ircbots@muffinmedic.net:~/discord-logger$ python setup.py install
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/discord
creating build/lib/discord/logging
copying src/logging/__init__.py -> build/lib/discord/logging
copying src/logging/daemon.py -> build/lib/discord/logging
copying src/logging/mixed.py -> build/lib/discord/logging
copying src/logging/scripting.py -> build/lib/discord/logging
running build_scripts
creating build/scripts-3.6
copying and adjusting src/dsclog -> build/scripts-3.6
changing mode of build/scripts-3.6/dsclog from 644 to 755
running install_lib
copying build/lib/discord/logging/__init__.py -> /home/ircbots/.pyenv/versions/discord-logger/lib/python3.6/site-packages/discord/logging
copying build/lib/discord/logging/daemon.py -> /home/ircbots/.pyenv/versions/discord-logger/lib/python3.6/site-packages/discord/logging
copying build/lib/discord/logging/mixed.py -> /home/ircbots/.pyenv/versions/discord-logger/lib/python3.6/site-packages/discord/logging
copying build/lib/discord/logging/scripting.py -> /home/ircbots/.pyenv/versions/discord-logger/lib/python3.6/site-packages/discord/logging
byte-compiling /home/ircbots/.pyenv/versions/discord-logger/lib/python3.6/site-packages/discord/logging/__init__.py to __init__.cpython-36.pyc
byte-compiling /home/ircbots/.pyenv/versions/discord-logger/lib/python3.6/site-packages/discord/logging/daemon.py to daemon.cpython-36.pyc
byte-compiling /home/ircbots/.pyenv/versions/discord-logger/lib/python3.6/site-packages/discord/logging/mixed.py to mixed.cpython-36.pyc
byte-compiling /home/ircbots/.pyenv/versions/discord-logger/lib/python3.6/site-packages/discord/logging/scripting.py to scripting.cpython-36.pyc
running install_scripts
copying build/scripts-3.6/dsclog -> /home/ircbots/.pyenv/versions/discord-logger/bin
changing mode of /home/ircbots/.pyenv/versions/discord-logger/bin/dsclog to 755
running install_egg_info
Removing /home/ircbots/.pyenv/versions/discord-logger/lib/python3.6/site-packages/discord_logger-0.0.1-py3.6.egg-info
Writing /home/ircbots/.pyenv/versions/discord-logger/lib/python3.6/site-packages/discord_logger-0.0.1-py3.6.egg-info
Traceback (most recent call last):
  File "setup.py", line 75, in <module>
    requires=REQUIRES
  File "/home/ircbots/.pyenv/versions/3.6.2/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/ircbots/.pyenv/versions/3.6.2/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/ircbots/.pyenv/versions/3.6.2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ircbots/.pyenv/versions/3.6.2/lib/python3.6/distutils/command/install.py", line 557, in run
    self.run_command(cmd_name)
  File "/home/ircbots/.pyenv/versions/3.6.2/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ircbots/.pyenv/versions/3.6.2/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ircbots/.pyenv/versions/3.6.2/lib/python3.6/distutils/command/install_egg_info.py", line 44, in run
    self.distribution.metadata.write_pkg_file(f)
  File "/home/ircbots/.pyenv/versions/3.6.2/lib/python3.6/distutils/dist.py", line 1127, in write_pkg_file
    long_desc = rfc822_escape(self.get_long_description())
  File "/home/ircbots/.pyenv/versions/3.6.2/lib/python3.6/distutils/util.py", line 474, in rfc822_escape
    lines = header.split('\n')
AttributeError: 'list' object has no attribute 'split'
(discord-logger) ircbots@muffinmedic.net:~/discord-logger$ 
```

**Comment by MuffinMedic** [comment]
Bump
